name: tag

on:
  workflow_call:
    outputs:
      tag:
        description: The latest tag (e.g. v0.0.0)
        value: ${{ jobs.tag.outputs.tag }}
      tag_without_version:
        description: The latest tag without the version (e.g. 0.0.0)
        value: ${{ jobs.tag.outputs.new_version }}

jobs:
  tag:
    # Only push tag on main branch
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
      tag_without_version: ${{ steps.tag_version.outputs.new_version }}

    steps:
      - name: Checkout git commit
        uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
